/-
Copyright (c) 2026 Nelson Spence. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nelson Spence
-/

import OrdvecFormalization.Examples
import OrdvecFormalization.VerifyMovedImports
import OrdvecFormalization.BitmapNull
import OrdvecFormalization.BitmapSymmetry
import OrdvecFormalization.FiniteExperiment
import OrdvecFormalization.FiniteBayesRisk
import OrdvecFormalization.OrdinalSufficiency
import OrdvecFormalization.CalibratedEvidence
import OrdvecFormalization.OverlapSufficiency
import OrdvecFormalization.CanonicalTilt
import OrdvecFormalization.OverlapBayesOptimal
import OrdvecFormalization.BitmapIncidence
import OrdvecFormalization.BitmapCalibration

namespace OrdvecFormalization

/-!
# Public API verification
-/

#check @BitmapCoord
#check @constantWeightBitmapSpace
#check @mem_constantWeightBitmapSpace_iff
#check @card_constantWeightBitmapSpace
#check @constantWeightBitmapSpace_nonempty
#check @bitmapOverlap
#check @bitmapOverlapFiber
#check @mem_bitmapOverlapFiber_iff
#check @bitmapOverlapTailEvent
#check @mem_bitmapOverlapTailEvent_iff
#check @bitmapComplement
#check @card_bitmapComplement
#check @insideOutsideChoices
#check @mem_insideOutsideChoices_iff
#check @card_insideOutsideChoices
#check @bitmapHypergeomNumerator
#check @card_insideOutsideChoices_of_query_card
#check @card_bitmapOverlapFiber_of_query_card
#check @bitmapHypergeomMass
#check @bitmapHypergeomMass_eq_insideOutsideChoices_card_ratio
#check @bitmapHypergeomMass_eq_overlapFiber_card_ratio
#check @bitmapHypergeomTail
#check @bitmapOverlapTailMass
#check @card_bitmapOverlapTailEvent_eq_sum_overlapFiber_card_of_query_card
#check @bitmapOverlapTailMass_eq_bitmapHypergeomTail_of_query_card
#check @bitmapUniformPMF
#check @bitmapUniformPMF_apply
#check @bitmapUniformPMF_overlapFiber_prob
#check @bitmapUniformPMF_overlapTail_prob
#check @BitmapPerm
#check @queryStabilizer
#check @permuteBitmap
#check @bitmapQueryPart
#check @bitmapQueryComplPart
#check @mem_bitmapQueryPart_iff
#check @mem_bitmapQueryComplPart_iff
#check @card_bitmapQueryPart_eq_overlap
#check @card_bitmapQueryComplPart_eq_card_sub_overlap
#check @card_bitmapQueryPart_eq_of_overlap_eq
#check @card_bitmapQueryComplPart_eq_of_card_eq_of_overlap_eq
#check @mem_permuteBitmap_iff
#check @card_permuteBitmap
#check @mem_constantWeightBitmapSpace_permuteBitmap_iff
#check @permuteBitmap_mem_constantWeightBitmapSpace
#check @mem_queryStabilizer_iff
#check @queryStabilizer_apply_mem_iff
#check @bitmapOverlap_queryStabilizer_eq
#check @bitmapOverlap_eq_of_mem_queryStabilizer_orbit
#check @subtypeCongr_query_mem_iff
#check @subtypeCongr_mem_queryStabilizer
#check @subtypeCongr_permuteBitmap_eq_of_parts
#check @exists_queryStabilizer_permuteBitmap_eq_of_card_eq_overlap_eq
#check @exists_queryStabilizer_permuteBitmap_eq_iff_overlap_eq_of_card_eq
#check @invariantOn_constantWeightBitmapSpace_eq_of_overlap_eq
#check @invariantOn_constantWeightBitmapSpace_factorsThrough_overlap
#check @FiniteLaw
#check @finiteLawOfPosPMF
#check @finiteWeightedBayesAdmit
#check @finiteWeightedBayesAdmitSet
#check @finiteWeightedRisk
#check @finiteLawProb
#check @finiteWeightedBayesAdmitSet_optimal
#check @quotientPullback
#check @RuleFactorsThrough
#check @RulePredicts
#check @mem_quotientPullback_of_quotient_preserving
#check @FiniteBayesAdmitFactorsThrough
#check @quotientBayesAdmitSet
#check @quotientBayesAdmitSet_pullback_eq
#check @exists_quotientPullback_finiteWeightedRisk_le
#check @finiteLikelihoodRatio
#check @FiniteLikelihoodRatioFactorsThrough
#check @finiteWeightedBayesAdmit_iff_cutoff_le_likelihoodRatio
#check @finiteBayesAdmitFactorsThrough_of_likelihoodRatioFactorsThrough
#check @exists_quotientPullback_finiteWeightedRisk_le_of_likelihoodRatioFactorsThrough
#check @orderedQuotientThresholdSet
#check @FiniteLikelihoodRatioFactorsThroughOrderedEvidence
#check @exists_orderedQuotientThreshold_finiteWeightedRisk_le_of_monotone
#check @exists_orderedQuotientThreshold_finiteWeightedRisk_le_of_orderedEvidenceFactor
#check @OrderedTailCalibration
#check @exists_calibratedOrderedThreshold_finiteBayesRisk_le_of_orderedEvidenceFactor
#check @exists_calibratedOrderedThreshold_finiteCostedBayesRisk_le_of_orderedEvidenceFactor
#check @overlapQuotientThresholdSet
#check @overlapQuotientThresholdSet_eq_orderedQuotientThresholdSet
#check @FiniteLikelihoodRatioFactorsThroughOverlapEvidence
#check @exists_overlapQuotientThreshold_finiteWeightedRisk_le_of_overlapEvidenceFactor
#check @exists_overlapQuotientThreshold_finiteWeightedRisk_le_of_likelihoodRatioFactor
#check @finiteTiltWeight
#check @finiteTiltNormalizer
#check @finiteExponentialTilt
#check @finiteTiltWeight_zero
#check @finiteTiltNormalizer_zero
#check @finiteExponentialTilt_zero_mass
#check @finiteExponentialTiltLikelihoodFactor
#check @finiteLikelihoodRatio_finiteExponentialTilt_eq_factor
#check @nnexp_ratio_monotone
#check @finiteExponentialTiltLikelihoodFactor_monotone
#check @finiteExponentialTilt_likelihoodRatioFactorsThroughOrderedEvidence
#check @finiteExponentialTilt_likelihoodRatioFactorsThroughOverlapEvidence
#check @exists_overlapQuotientThreshold_finiteWeightedRisk_le_of_finiteExponentialTilt
#check @exists_overlapQuotientThreshold_finiteWeightedRisk_le_of_canonicalTilt
#check @finiteBayesRisk
#check @finiteCostedBayesRisk
#check @exists_overlapQuotientThreshold_finiteBayesRisk_le_of_canonicalTilt
#check @exists_overlapQuotientThreshold_finiteBayesRisk_le_of_canonicalTilt_of_lt
#check @exists_overlapQuotientThreshold_finiteCostedBayesRisk_le_of_canonicalTilt
#check @exists_overlapQuotientThreshold_finiteCostedBayesRisk_le_of_canonicalTilt_of_lt
#check @bitmapOverlapParams
#check @BitmapCut
#check @bitmapCutThreshold
#check @ConstantWeightBitmap
#check @constantWeightBitmap_card
#check @constantWeightBitmapUniformLaw
#check @constantWeightBitmapOverlapTailSet
#check @bitmapOverlapParams_lo_le_overlap
#check @bitmapOverlap_le_bitmapOverlapParams_hi
#check @constantWeightBitmapOverlapEvidence
#check @constantWeightBitmapOverlapEvidence_overlap
#check @overlapQuotientThresholdSet_constantWeightBitmapOverlapEvidence_eq
#check @constantWeightBitmapOverlapTailCalibration
#check @exists_overlapQuotientThreshold_finiteBayesRisk_le_and_bitmapHypergeomTail
#check @exists_overlapQuotientThreshold_finiteCostedBayesRisk_le_and_bitmapHypergeomTail
#check @exists_constantWeightBitmapOverlapTail_finiteBayesRisk_le_and_hypergeomTail
#check @exists_constantWeightBitmapOverlapTail_finiteCostedBayesRisk_le_and_hypergeomTail
#check @exists_uniformBitmapOverlapTail_finiteBayesRisk_le_and_hypergeomTail
#check @exists_uniformBitmapOverlapTail_finiteCostedBayesRisk_le_and_hypergeomTail
#check @QuotientFiberExampleObs
#check @quotientFiberExampleQuotient
#check @quotientFiberExampleQuotientTarget
#check @quotientFiberExampleFiberTarget
#check @quotientFiberExample_quotientTarget_factorsThrough
#check @quotientFiberExample_quotientTarget_predictable_by_quotient
#check @quotientFiberExample_fiberTarget_predictable_by_fullObservation
#check @quotientFiberExample_fiberTarget_not_factorsThrough
#check @quotientFiberExample_quotientTarget_factorsThrough_not_fiberTarget
#check @Prior
#check @DecisionCosts
#check @weightedBayesAdmit
#check @costedBayesAdmit
#check @mlr_monotone_bayesAdmit
#check @mlr_monotone_weightedBayesAdmit
#check @likelihoodRatio
#check @weightedLikelihoodCutoff
#check @priorOddsCutoff
#check @weightedBayesAdmit_iff_cutoff_le_likelihoodRatio
#check @bayesAdmit_iff_priorOddsCutoff_le_likelihoodRatio
#check @weightedBayesAdmit_isThreshold
#check @bayesAdmit_isThreshold
#check @costedBayesAdmit_isThreshold
#check @weightedBayesRisk
#check @threshold_bayesRisk_optimal
#check @weighted_threshold_bayesRisk_optimal
#check @costedBayesRisk
#check @costed_threshold_bayesRisk_optimal
#check @exponentialTilt_hasMLR
#check @exponentialTilt_hasMLR_of_lt
#check @exponentialTilt_bayesAdmit_isThreshold
#check @exponentialTilt_threshold_bayesRisk_optimal
#check @exponentialTilt_costedBayesAdmit_isThreshold
#check @exponentialTilt_costed_threshold_bayesRisk_optimal
#check @fnch_hasMLR
#check @fnch_hasMLR_of_lt
#check @fnch_bayesAdmit_isThreshold
#check @fnch_threshold_bayesRisk_optimal
#check @fnch_costedBayesAdmit_isThreshold
#check @fnch_costed_threshold_bayesRisk_optimal
#check @fnch_bayesAdmit_isActualOverlapThreshold
#check @fnch_actualOverlapThreshold_bayesRisk_optimal
#check @fnch_costedBayesAdmit_isActualOverlapThreshold
#check @fnch_costed_actualOverlapThreshold_bayesRisk_optimal
#check @fnchActualPMF_mass_eq_fnchPMF_mass
#check @fnchActual_hasMLR
#check @fnchActual_hasMLR_of_lt
#check @fnchActual_bayesAdmit_isActualOverlapThreshold
#check @fnchActual_actualOverlapThreshold_bayesRisk_optimal
#check @fnchActual_costedBayesAdmit_isActualOverlapThreshold
#check @fnchActual_costed_actualOverlapThreshold_bayesRisk_optimal
#check @fnchActual_bayesAdmit_isActualOverlapThreshold_of_lt
#check @fnchActual_actualOverlapThreshold_bayesRisk_optimal_of_lt
#check @fnchActual_costedBayesAdmit_isActualOverlapThreshold_of_lt
#check @fnchActual_costed_actualOverlapThreshold_bayesRisk_optimal_of_lt
#check @overlapNull_fnch_hasMLR
#check @overlapNull_bayesAdmit_isThreshold
#check @overlapNull_threshold_bayesRisk_optimal
#check @overlapNull_threshold_bayesRisk_optimal_of_lt
#check @overlapNull_costed_bayesAdmit_isThreshold
#check @overlapNull_costed_threshold_bayesRisk_optimal
#check @overlapNull_costed_threshold_bayesRisk_optimal_of_lt
#check @fnchActual_overlap_hasMLR_of_lt
#check @fnch_overlap_admit_threshold
#check @fnch_overlap_threshold_bayes_optimal
#check @fnch_overlap_costed_threshold_bayes_optimal
#check @exampleFNCHParams
#check @balancedPrior
#check @balancedPrior_pos
#check @unitDecisionCosts
#check @unitDecisionCosts_falseReject_mul_balancedPrior_pos

#print axioms mem_constantWeightBitmapSpace_iff
#print axioms card_constantWeightBitmapSpace
#print axioms constantWeightBitmapSpace_nonempty
#print axioms mem_bitmapOverlapFiber_iff
#print axioms mem_bitmapOverlapTailEvent_iff
#print axioms card_bitmapComplement
#print axioms mem_insideOutsideChoices_iff
#print axioms card_insideOutsideChoices
#print axioms card_insideOutsideChoices_of_query_card
#print axioms card_bitmapOverlapFiber_of_query_card
#print axioms bitmapHypergeomMass_eq_insideOutsideChoices_card_ratio
#print axioms bitmapHypergeomMass_eq_overlapFiber_card_ratio
#print axioms card_bitmapOverlapTailEvent_eq_sum_overlapFiber_card_of_query_card
#print axioms bitmapOverlapTailMass_eq_bitmapHypergeomTail_of_query_card
#print axioms bitmapUniformPMF_apply
#print axioms bitmapUniformPMF_overlapFiber_prob
#print axioms bitmapUniformPMF_overlapTail_prob
#print axioms bitmapOverlap_queryStabilizer_eq
#print axioms exists_queryStabilizer_permuteBitmap_eq_of_card_eq_overlap_eq
#print axioms exists_queryStabilizer_permuteBitmap_eq_iff_overlap_eq_of_card_eq
#print axioms invariantOn_constantWeightBitmapSpace_factorsThrough_overlap
#print axioms finiteWeightedBayesAdmitSet_optimal
#print axioms finiteLawProb
#print axioms mem_quotientPullback_of_quotient_preserving
#print axioms quotientBayesAdmitSet_pullback_eq
#print axioms exists_quotientPullback_finiteWeightedRisk_le
#print axioms finiteWeightedBayesAdmit_iff_cutoff_le_likelihoodRatio
#print axioms finiteBayesAdmitFactorsThrough_of_likelihoodRatioFactorsThrough
#print axioms exists_quotientPullback_finiteWeightedRisk_le_of_likelihoodRatioFactorsThrough
#print axioms exists_orderedQuotientThreshold_finiteWeightedRisk_le_of_monotone
#print axioms exists_orderedQuotientThreshold_finiteWeightedRisk_le_of_orderedEvidenceFactor
#print axioms OrderedTailCalibration
#print axioms exists_calibratedOrderedThreshold_finiteBayesRisk_le_of_orderedEvidenceFactor
#print axioms exists_calibratedOrderedThreshold_finiteCostedBayesRisk_le_of_orderedEvidenceFactor
#print axioms overlapQuotientThresholdSet_eq_orderedQuotientThresholdSet
#print axioms exists_overlapQuotientThreshold_finiteWeightedRisk_le_of_overlapEvidenceFactor
#print axioms exists_overlapQuotientThreshold_finiteWeightedRisk_le_of_likelihoodRatioFactor
#print axioms finiteLikelihoodRatio_finiteExponentialTilt_eq_factor
#print axioms finiteTiltWeight_zero
#print axioms finiteTiltNormalizer_zero
#print axioms finiteExponentialTilt_zero_mass
#print axioms nnexp_ratio_monotone
#print axioms finiteExponentialTiltLikelihoodFactor_monotone
#print axioms finiteExponentialTilt_likelihoodRatioFactorsThroughOrderedEvidence
#print axioms finiteExponentialTilt_likelihoodRatioFactorsThroughOverlapEvidence
#print axioms exists_overlapQuotientThreshold_finiteWeightedRisk_le_of_finiteExponentialTilt
#print axioms exists_overlapQuotientThreshold_finiteWeightedRisk_le_of_canonicalTilt
#print axioms exists_overlapQuotientThreshold_finiteBayesRisk_le_of_canonicalTilt
#print axioms exists_overlapQuotientThreshold_finiteBayesRisk_le_of_canonicalTilt_of_lt
#print axioms exists_overlapQuotientThreshold_finiteCostedBayesRisk_le_of_canonicalTilt
#print axioms exists_overlapQuotientThreshold_finiteCostedBayesRisk_le_of_canonicalTilt_of_lt
#print axioms bitmapOverlapParams
#print axioms bitmapCutThreshold
#print axioms constantWeightBitmap_card
#print axioms constantWeightBitmapUniformLaw
#print axioms constantWeightBitmapOverlapTailSet
#print axioms bitmapOverlapParams_lo_le_overlap
#print axioms bitmapOverlap_le_bitmapOverlapParams_hi
#print axioms constantWeightBitmapOverlapEvidence
#print axioms constantWeightBitmapOverlapEvidence_overlap
#print axioms overlapQuotientThresholdSet_constantWeightBitmapOverlapEvidence_eq
#print axioms constantWeightBitmapOverlapTailCalibration
#print axioms exists_overlapQuotientThreshold_finiteBayesRisk_le_and_bitmapHypergeomTail
#print axioms exists_overlapQuotientThreshold_finiteCostedBayesRisk_le_and_bitmapHypergeomTail
#print axioms exists_constantWeightBitmapOverlapTail_finiteBayesRisk_le_and_hypergeomTail
#print axioms exists_constantWeightBitmapOverlapTail_finiteCostedBayesRisk_le_and_hypergeomTail
#print axioms exists_uniformBitmapOverlapTail_finiteBayesRisk_le_and_hypergeomTail
#print axioms exists_uniformBitmapOverlapTail_finiteCostedBayesRisk_le_and_hypergeomTail
#print axioms quotientFiberExample_quotientTarget_factorsThrough
#print axioms quotientFiberExample_quotientTarget_predictable_by_quotient
#print axioms quotientFiberExample_fiberTarget_predictable_by_fullObservation
#print axioms quotientFiberExample_fiberTarget_not_factorsThrough
#print axioms quotientFiberExample_quotientTarget_factorsThrough_not_fiberTarget
#print axioms mlr_monotone_bayesAdmit
#print axioms mlr_monotone_weightedBayesAdmit
#print axioms weightedBayesAdmit_iff_cutoff_le_likelihoodRatio
#print axioms bayesAdmit_iff_priorOddsCutoff_le_likelihoodRatio
#print axioms weightedBayesAdmit_isThreshold
#print axioms bayesAdmit_isThreshold
#print axioms costedBayesAdmit_isThreshold
#print axioms threshold_bayesRisk_optimal
#print axioms weighted_threshold_bayesRisk_optimal
#print axioms costed_threshold_bayesRisk_optimal
#print axioms exponentialTilt_hasMLR
#print axioms exponentialTilt_hasMLR_of_lt
#print axioms exponentialTilt_bayesAdmit_isThreshold
#print axioms exponentialTilt_threshold_bayesRisk_optimal
#print axioms exponentialTilt_costedBayesAdmit_isThreshold
#print axioms exponentialTilt_costed_threshold_bayesRisk_optimal
#print axioms fnch_hasMLR
#print axioms fnch_hasMLR_of_lt
#print axioms fnch_bayesAdmit_isThreshold
#print axioms fnch_threshold_bayesRisk_optimal
#print axioms fnch_costedBayesAdmit_isThreshold
#print axioms fnch_costed_threshold_bayesRisk_optimal
#print axioms fnch_bayesAdmit_isActualOverlapThreshold
#print axioms fnch_actualOverlapThreshold_bayesRisk_optimal
#print axioms fnch_costedBayesAdmit_isActualOverlapThreshold
#print axioms fnch_costed_actualOverlapThreshold_bayesRisk_optimal
#print axioms fnchActualPMF_mass_eq_fnchPMF_mass
#print axioms fnchActual_hasMLR
#print axioms fnchActual_hasMLR_of_lt
#print axioms fnchActual_bayesAdmit_isActualOverlapThreshold
#print axioms fnchActual_actualOverlapThreshold_bayesRisk_optimal
#print axioms fnchActual_costedBayesAdmit_isActualOverlapThreshold
#print axioms fnchActual_costed_actualOverlapThreshold_bayesRisk_optimal
#print axioms fnchActual_bayesAdmit_isActualOverlapThreshold_of_lt
#print axioms fnchActual_actualOverlapThreshold_bayesRisk_optimal_of_lt
#print axioms fnchActual_costedBayesAdmit_isActualOverlapThreshold_of_lt
#print axioms fnchActual_costed_actualOverlapThreshold_bayesRisk_optimal_of_lt
#print axioms overlapNull_fnch_hasMLR
#print axioms overlapNull_bayesAdmit_isThreshold
#print axioms overlapNull_threshold_bayesRisk_optimal
#print axioms overlapNull_threshold_bayesRisk_optimal_of_lt
#print axioms overlapNull_costed_bayesAdmit_isThreshold
#print axioms overlapNull_costed_threshold_bayesRisk_optimal
#print axioms overlapNull_costed_threshold_bayesRisk_optimal_of_lt
#print axioms fnchActual_overlap_hasMLR_of_lt
#print axioms fnch_overlap_admit_threshold
#print axioms fnch_overlap_threshold_bayes_optimal
#print axioms fnch_overlap_costed_threshold_bayes_optimal

end OrdvecFormalization
